# Generated by Django 2.1.5 on 2019-04-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=40)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Reg_No', models.CharField(max_length=11)),
                ('Engine_Numer', models.CharField(max_length=40)),
                ('Bike_Model', models.CharField(max_length=35)),
                ('Color', models.CharField(max_length=25)),
                ('Remarks', models.TimeField(max_length=159)),
                ('Valid_From', models.DateTimeField()),
                ('Valid_To', models.DateTimeField()),
            ],
        ),
    ]
