# Generated by Django 2.1.5 on 2019-04-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SidApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motors',
            name='Remarks',
            field=models.TextField(max_length=159),
        ),
    ]
