# Generated by Django 2.1.5 on 2019-04-17 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SidApp', '0002_auto_20190415_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motors',
            name='Mobile_Number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
