# Generated by Django 2.1.5 on 2019-04-17 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SidApp', '0003_auto_20190417_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clip', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='motors',
            name='Mobile_Number',
            field=models.CharField(help_text='Please Enter Valid 10 Digit Mobile Number,If Not Consumer Data Wil Not Save.', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
