# Generated by Django 2.1.5 on 2019-04-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SidApp', '0004_auto_20190417_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
